/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reading.ui;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashMap;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import com.reading.actionListener.Authenticate;
import com.reading.actionListener.SearchDropdownItem;
import com.reading.operaton.DateTime;
import com.reading.operaton.SetAllTable;
import com.reading.operaton.processImage.SetImage;

/**
 *
 * @author Sawant
 */
public class Home extends javax.swing.JFrame {

	JInternalFrame frame = new JInternalFrame();
	public JInternalFrame frame2 = new JInternalFrame();
	public static String user;
	JInternalFrame frm = new JInternalFrame();
	JLabel clicked;
	LogIn login;

	/**
	 * Creates new form Home
	 */
	public Home() {

	}

	public Home(LogIn login) {

		initComponents();
		this.login = login;
		this.setExtendedState(this.MAXIMIZED_BOTH);
		this.getContentPane().setBackground(Color.white);
		conformCloseSoftware();
		new SetAllTable().setHomeInfo();
		new DateTime();
		new SearchDropdownItem(nameCmb);
		this.clicked = homeLB;
		setImgs();
	}

	private void setImgs() {
		setIconImage(new SetImage().image("images/book.png"));
		homeLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/home2.png")));
		banner.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/logo.jpg")));
		utype.setText(Authenticate.usertype);
	}

	public void conformCloseSoftware() {
		this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent we) {
				String ObjButtons[] = { "Yes", "No" };
				int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure you want to exit?",
						"Reading System", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons,
						ObjButtons[1]);
				if (PromptResult == JOptionPane.YES_OPTION) {
					System.exit(0);
				}
			}
		});
	}

	public void mouseEntered(JLabel lbl) {
//        lbl.setFont(new java.awt.Font("Tahoma", 1, 14));
		lbl.setForeground(Color.white);
	}

	private void mouseExited(JLabel lbl) {
//        lbl.setFont(new java.awt.Font("Tahoma", 0, 13));
		lbl.setForeground(Color.black);
	}

	private void mouseHover(JLabel lbl, String img) {
		if (!(clicked == lbl)) {
			lbl.setIcon(new javax.swing.ImageIcon(new SetImage().image(img)));
		}
	}

	private void mouseOut(JLabel lbl, String img) {
		if (!(clicked == lbl)) {
			lbl.setIcon(new javax.swing.ImageIcon(new SetImage().image(img)));
		}
	}

	private void setAllBtnImages() {
		// set all images hear
		homeLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/home1.png")));
		settingLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/settings1.png")));
		summaryLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/summary1.png")));
		logsLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/logs1.png")));
		closeAdmissionLB
				.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/closed admission1.png")));
		ExpencesLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/expences1.png")));
		allStudentLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/all students1.png")));
		newAdmissionLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/new admission1.png")));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        settingLB = new javax.swing.JLabel();
        summaryLB = new javax.swing.JLabel();
        logsLB = new javax.swing.JLabel();
        closeAdmissionLB = new javax.swing.JLabel();
        ExpencesLB = new javax.swing.JLabel();
        allStudentLB = new javax.swing.JLabel();
        newAdmissionLB = new javax.swing.JLabel();
        homeLB = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        windo = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pendingLbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        activeLbl = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        closedLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        nameCmb = new javax.swing.JComboBox();
        searchBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Success Park Abhyasika");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        settingLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sawant\\Desktop\\images spa\\btn's\\settings1.png")); // NOI18N
        settingLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingLBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingLBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingLBMousePressed(evt);
            }
        });

        summaryLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sawant\\Desktop\\images spa\\btn's\\summary1.png")); // NOI18N
        summaryLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                summaryLBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                summaryLBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                summaryLBMousePressed(evt);
            }
        });

        logsLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sawant\\Desktop\\images spa\\btn's\\logs1.png")); // NOI18N
        logsLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logsLBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logsLBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logsLBMousePressed(evt);
            }
        });

        closeAdmissionLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sawant\\Desktop\\images spa\\btn's\\closed admission1.png")); // NOI18N
        closeAdmissionLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeAdmissionLBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeAdmissionLBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeAdmissionLBMousePressed(evt);
            }
        });

        ExpencesLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sawant\\Desktop\\images spa\\btn's\\expences1.png")); // NOI18N
        ExpencesLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExpencesLBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExpencesLBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExpencesLBMousePressed(evt);
            }
        });

        allStudentLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sawant\\Desktop\\images spa\\btn's\\all students1.png")); // NOI18N
        allStudentLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allStudentLBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allStudentLBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                allStudentLBMousePressed(evt);
            }
        });

        newAdmissionLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sawant\\Desktop\\images spa\\btn's\\new admission1.png")); // NOI18N
        newAdmissionLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newAdmissionLBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newAdmissionLBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newAdmissionLBMousePressed(evt);
            }
        });

        homeLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sawant\\Desktop\\images spa\\btn's\\home1.png")); // NOI18N
        homeLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeLBMousePressed(evt);
            }
        });

        banner.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(settingLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(summaryLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logsLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeAdmissionLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExpencesLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allStudentLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newAdmissionLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(banner))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newAdmissionLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allStudentLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExpencesLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeAdmissionLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logsLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summaryLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingLB)
                .addGap(77, 77, 77))
        );

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel5.setText("View Detail");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setText(">>>");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jLabel3.setText("Total Number Of");

        jLabel4.setText("Pending Fees Students");

        pendingLbl.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        pendingLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pendingLbl.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(pendingLbl)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pendingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel7.setText("View Detail");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setText(">>>");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16))
                .addContainerGap())
        );

        jLabel12.setText("Total Number Of ");

        jLabel20.setText("Active Students");

        activeLbl.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        activeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        activeLbl.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(activeLbl)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        jLabel9.setText("  LOG OUT");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel18.setText(">>>");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        dateLbl.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(255, 255, 255));
        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLbl.setText("jLabel23");

        timeLbl.setBackground(new java.awt.Color(0, 102, 102));
        timeLbl.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        timeLbl.setForeground(new java.awt.Color(255, 255, 255));
        timeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLbl.setText("jLabel24");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User name");

        utype.setText("utype");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(dateLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeLbl))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(utype)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utype))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLbl)
                    .addComponent(timeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 102, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel8.setText("View Detail");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setText(">>>");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jLabel11.setText("Total Number Of");

        jLabel21.setText("Closed Admission ");

        closedLbl.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        closedLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        closedLbl.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 70)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("success park abhyasika");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel19.setText("Select Student Name");

        nameCmb.setEditable(true);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Submit Fees");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(nameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(nameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout windoLayout = new javax.swing.GroupLayout(windo);
        windo.setLayout(windoLayout);
        windoLayout.setHorizontalGroup(
            windoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(windoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        windoLayout.setVerticalGroup(
            windoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(windoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        windo.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        windo.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        windo.setLayer(jPanel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        windo.setLayer(jPanel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        windo.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        windo.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(windo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
//		frame.dispose();
//		frame = new StudentSummaryUI();
//		windo.add(frame);
//		frame.setVisible(true);
////            clicked = summaryLB;
//		setAllBtnImages();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void homeLBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_homeLBMouseEntered
		// TODO add your handling code here:
		mouseHover(homeLB, "images/buttons/home2.png");
	}// GEN-LAST:event_homeLBMouseEntered

	private void homeLBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_homeLBMouseExited
		// TODO add your handling code here:
		mouseOut(homeLB, "images/buttons/home1.png");
	}// GEN-LAST:event_homeLBMouseExited

	private void homeLBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_homeLBMousePressed
		// TODO add your handling code here:
		frame.dispose();
		try {
			frame2.dispose();
		} catch (Exception e) {
//			System.out.println("Ignorable NullPointer, second leve frame not found");
		}
		clicked = homeLB;
		setAllBtnImages();
		homeLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/home2.png")));
	}// GEN-LAST:event_homeLBMousePressed

	private void settingLBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_settingLBMouseEntered
		// TODO add your handling code here:
		mouseHover(settingLB, "images/buttons/setting2.png");
	}// GEN-LAST:event_settingLBMouseEntered

	private void settingLBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_settingLBMouseExited
		// TODO add your handling code here:
		mouseOut(settingLB, "images/buttons/settings1.png");
	}// GEN-LAST:event_settingLBMouseExited

	private void settingLBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_settingLBMousePressed
		// TODO add your handling code here:
		if (Authenticate.usertype.equalsIgnoreCase("Admin")) {
			frame.dispose();
			frame = new SettingsUI(this);
			windo.add(frame);
			frame.setVisible(true);
			clicked = settingLB;
			setAllBtnImages();
			settingLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/setting2.png")));
		}
	}// GEN-LAST:event_settingLBMousePressed

	private void summaryLBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_summaryLBMouseEntered
		// TODO add your handling code here:
		mouseHover(summaryLB, "images/buttons/summary2.png");
	}// GEN-LAST:event_summaryLBMouseEntered

	private void summaryLBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_summaryLBMouseExited
		// TODO add your handling code here:
		mouseOut(summaryLB, "images/buttons/summary1.png");
	}// GEN-LAST:event_summaryLBMouseExited

	private void summaryLBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_summaryLBMousePressed
		// TODO add your handling code here:
		if (Authenticate.usertype.equalsIgnoreCase("Admin")) {
			frame.dispose();
			frame = new SummaryUi(this);
			windo.add(frame);
			frame.setVisible(true);
			clicked = summaryLB;
			setAllBtnImages();
			summaryLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/summary2.png")));
		}
	}// GEN-LAST:event_summaryLBMousePressed

	private void logsLBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logsLBMouseEntered
		// TODO add your handling code here:
		mouseHover(logsLB, "images/buttons/logs2.png");
	}// GEN-LAST:event_logsLBMouseEntered

	private void logsLBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logsLBMouseExited
		// TODO add your handling code here:
		mouseOut(logsLB, "images/buttons/logs1.png");
	}// GEN-LAST:event_logsLBMouseExited

	private void logsLBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logsLBMousePressed
		// TODO add your handling code here:
		if (Authenticate.usertype.equalsIgnoreCase("Admin")) {
			frame.dispose();
			frame = new ActionTracker(this);
			windo.add(frame);
			frame.setVisible(true);
			clicked = logsLB;
			setAllBtnImages();
			logsLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/logs2.png")));
		}
	}// GEN-LAST:event_logsLBMousePressed

	private void closeAdmissionLBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeAdmissionLBMouseEntered
		// TODO add your handling code here:
		mouseHover(closeAdmissionLB, "images/buttons/closed admission2.png");
	}// GEN-LAST:event_closeAdmissionLBMouseEntered

	private void closeAdmissionLBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeAdmissionLBMouseExited
		// TODO add your handling code here:
		mouseOut(closeAdmissionLB, "images/buttons/closed admission1.png");
	}// GEN-LAST:event_closeAdmissionLBMouseExited

	private void closeAdmissionLBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeAdmissionLBMousePressed
		// TODO add your handling code here:
		if (Authenticate.usertype.equalsIgnoreCase("Admin")) {
			frame.dispose();
			frame = new ClosedAdmissions(this);
			windo.add(frame);
			frame.setVisible(true);
			clicked = closeAdmissionLB;
			setAllBtnImages();
			closeAdmissionLB
					.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/closed admission2.png")));
		}
	}// GEN-LAST:event_closeAdmissionLBMousePressed

	private void ExpencesLBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ExpencesLBMouseEntered
		// TODO add your handling code here:
		mouseHover(ExpencesLB, "images/buttons/expences2.png");
	}// GEN-LAST:event_ExpencesLBMouseEntered

	private void ExpencesLBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ExpencesLBMouseExited
		// TODO add your handling code here:
		mouseOut(ExpencesLB, "images/buttons/expences1.png");
	}// GEN-LAST:event_ExpencesLBMouseExited

	private void ExpencesLBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ExpencesLBMousePressed
		// TODO add your handling code here:
		frame.dispose();
		frame = new Expences(this);
		windo.add(frame);
		frame.setVisible(true);
		clicked = ExpencesLB;
		setAllBtnImages();
		ExpencesLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/expences2.png")));
	}// GEN-LAST:event_ExpencesLBMousePressed

	private void allStudentLBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_allStudentLBMouseEntered
		// TODO add your handling code here:
		mouseHover(allStudentLB, "images/buttons/all students2.png");
	}// GEN-LAST:event_allStudentLBMouseEntered

	private void allStudentLBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_allStudentLBMouseExited
		// TODO add your handling code here:
		mouseOut(allStudentLB, "images/buttons/all students1.png");
	}// GEN-LAST:event_allStudentLBMouseExited

	private void allStudentLBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_allStudentLBMousePressed
		// TODO add your handling code here:
		frame.dispose();
//		frame = new AllStudents(this);
		frame = new StudentSummaryUI(this);
		windo.add(frame);
		frame.setVisible(true);
		clicked = allStudentLB;
		setAllBtnImages();
		allStudentLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/all students2.png")));
	}// GEN-LAST:event_allStudentLBMousePressed

	private void newAdmissionLBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_newAdmissionLBMouseEntered
		// TODO add your handling code here:
		mouseHover(newAdmissionLB, "images/buttons/new admission2.png");
	}// GEN-LAST:event_newAdmissionLBMouseEntered

	private void newAdmissionLBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_newAdmissionLBMouseExited
		// TODO add your handling code here:
		mouseOut(newAdmissionLB, "images/buttons/new admission1.png");
	}// GEN-LAST:event_newAdmissionLBMouseExited

	private void newAdmissionLBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_newAdmissionLBMousePressed
		// TODO add your handling code here:
		frame.dispose();
		frame = new NewAdmission();
		windo.add(frame);
		frame.setVisible(true);
		clicked = newAdmissionLB;
		setAllBtnImages();
		newAdmissionLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/new admission2.png")));
	}// GEN-LAST:event_newAdmissionLBMousePressed

	private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MousePressed
		// TODO add your handling code here:
		this.dispose();
		login.setVisible(true);
	}// GEN-LAST:event_jLabel9MousePressed

	private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel18MousePressed
		// TODO add your handling code here:
		this.dispose();
		login.setVisible(true);
	}// GEN-LAST:event_jLabel18MousePressed

	private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchBtnActionPerformed
		// TODO add your handling code here:
		String item = (String) nameCmb.getSelectedItem();
		if (!(null == item)) {
			String[] arr = item.split("-");
			String id = arr[1].trim();
			frm.dispose();
			frm = new SubmitFeesUI(id);
			windo.add(frm);
			frm.setVisible(true);
		}
	}// GEN-LAST:event_searchBtnActionPerformed

	private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel14MouseEntered
		// TODO add your handling code here:
		mouseEntered(jLabel14);
	}// GEN-LAST:event_jLabel14MouseEntered

	private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel14MouseExited
		// TODO add your handling code here:
		mouseExited(jLabel14);
	}// GEN-LAST:event_jLabel14MouseExited

	private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel16MouseEntered
		// TODO add your handling code here:
		mouseEntered(jLabel16);
	}// GEN-LAST:event_jLabel16MouseEntered

	private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel17MouseExited
		// TODO add your handling code here:
		mouseExited(jLabel17);
	}// GEN-LAST:event_jLabel17MouseExited

	private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel18MouseEntered
		// TODO add your handling code here:
		mouseEntered(jLabel18);
	}// GEN-LAST:event_jLabel18MouseEntered

	private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel16MouseExited
		// TODO add your handling code here:
		mouseExited(jLabel16);
	}// GEN-LAST:event_jLabel16MouseExited

	private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel17MouseEntered
		// TODO add your handling code here:
		mouseEntered(jLabel17);
	}// GEN-LAST:event_jLabel17MouseEntered

	private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel18MouseExited
		// TODO add your handling code here:
		mouseExited(jLabel18);
	}// GEN-LAST:event_jLabel18MouseExited

	public void pendingStatus() {
		HashMap<String, Integer> totlFees;
		SetAllTable st = new SetAllTable();
		AllStudents as = new AllStudents(this);
		totlFees = st.getTotalFees();
		st.setActiveStudentTable(as.table, totlFees);
		as.searchText.setText("PENDING");
		frame.dispose();
		frame = as;
		windo.add(frame);
		frame.setVisible(true);
		clicked = allStudentLB;
		setAllBtnImages();
		allStudentLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/all students2.png"))); // NOI18N
	}

	private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel14MouseClicked
		// TODO add your handling code here:
		pendingStatus();
	}// GEN-LAST:event_jLabel14MouseClicked

	public void activeStatus() {
		HashMap<String, Integer> totlFees;
		SetAllTable st = new SetAllTable();
		AllStudents as = new AllStudents(this);
		totlFees = st.getTotalFees();
		st.setActiveStudentTable(as.table, totlFees);
//        as.searchText.setText("PENDING");
		frame.dispose();
		frame = as;
		windo.add(frame);
		frame.setVisible(true);
		clicked = allStudentLB;
		setAllBtnImages();
		allStudentLB.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/all students2.png"))); // NOI18N
	}

	private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel16MouseClicked
		// TODO add your handling code here:
		activeStatus();
	}// GEN-LAST:event_jLabel16MouseClicked

	public void closedStatus() {
		frame.dispose();
		frame = new ClosedAdmissions(this);
		windo.add(frame);
		frame.setVisible(true); // TODO add your handling code here:
		setAllBtnImages();

		closeAdmissionLB
				.setIcon(new javax.swing.ImageIcon(new SetImage().image("images/buttons/closed admission2.png"))); // NOI18N
		clicked = closeAdmissionLB;
	}

	private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel17MouseClicked
		// TODO add your handling code here:
		closedStatus();
	}// GEN-LAST:event_jLabel17MouseClicked

	private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MouseClicked
		// TODO add your handling code here:
		pendingStatus();
	}// GEN-LAST:event_jLabel5MouseClicked

	private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel7MouseClicked
		// TODO add your handling code here:
		pendingStatus();
	}// GEN-LAST:event_jPanel7MouseClicked

	private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel7MouseClicked
		// TODO add your handling code here:
		activeStatus();
	}// GEN-LAST:event_jLabel7MouseClicked

	private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel8MouseClicked
		// TODO add your handling code here:
		activeStatus();
	}// GEN-LAST:event_jPanel8MouseClicked

	private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel8MouseClicked
		// TODO add your handling code here:
		closedStatus();
	}// GEN-LAST:event_jLabel8MouseClicked

	private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel13MouseClicked
		// TODO add your handling code here:
		closedStatus();
	}// GEN-LAST:event_jPanel13MouseClicked

	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExpencesLB;
    public static javax.swing.JLabel activeLbl;
    private javax.swing.JLabel allStudentLB;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel closeAdmissionLB;
    public static javax.swing.JLabel closedLbl;
    public static javax.swing.JLabel dateLbl;
    private javax.swing.JLabel homeLB;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logsLB;
    public static javax.swing.JComboBox nameCmb;
    private javax.swing.JLabel newAdmissionLB;
    public static javax.swing.JLabel pendingLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel settingLB;
    private javax.swing.JLabel summaryLB;
    public static javax.swing.JLabel timeLbl;
    private javax.swing.JLabel utype;
    public javax.swing.JDesktopPane windo;
    // End of variables declaration//GEN-END:variables
}
