package com.reading.ui;

import java.awt.Color;
import java.io.File;
import java.util.LinkedHashMap;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import com.reading.db.UsersDb;
import com.reading.hm.FixedFeesHM;
import com.reading.hm.UsersHM;
import com.reading.operaton.FormatFrame;
import com.reading.operaton.ImportExcel;
import com.reading.operaton.SetAllTable;
import com.reading.operaton.StaticMethods;
import com.reading.regx.RegX;
import com.reading.zip.GenerateZip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sawant
 */
public class SettingsUI extends javax.swing.JInternalFrame {
	RegX regx = new RegX();
	Home home;

	/**
	 * Creates new form SettingsUI
	 */
	public SettingsUI(Home home) {
		this.home = home;
		initComponents();
		new FormatFrame(this).formatTable(userTable);
		new SetAllTable().setUserToTable(userTable);
		getContentPane().setBackground(new Color(0, 153, 153));
		new SetAllTable().setFeesStructureToLable(this);
		StaticMethods.setCurrentDateToDropdown(dd, mm, yy);
		setIcons();
                userTable.setAutoResizeMode(userTable.AUTO_RESIZE_LAST_COLUMN);
	}

	public void setIcons() {
//		updateFFeesBtn.setIcon((Icon) new SetImage().image("update.png")); // NOI18N
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel16 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        monthLbl1 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        quarterLbl1 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        halfYearLbl1 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        yearLbl1 = new javax.swing.JLabel();
        dmTxt = new javax.swing.JTextField();
        dtTxt = new javax.swing.JTextField();
        dsTxt = new javax.swing.JTextField();
        dyTxt = new javax.swing.JTextField();
        nmTxt = new javax.swing.JTextField();
        ntTxt = new javax.swing.JTextField();
        nsTxt = new javax.swing.JTextField();
        nyTxt = new javax.swing.JTextField();
        dnmTxt = new javax.swing.JTextField();
        dntTxt = new javax.swing.JTextField();
        dnsTxt = new javax.swing.JTextField();
        dnyTxt = new javax.swing.JTextField();
        updateFFeesBtn = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        chooseFolderBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        folderTxt = new javax.swing.JTextArea();
        backupBtn = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        selectExcelBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        excelPath = new javax.swing.JTextArea();
        importBtb = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        jPanel18 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        deleteUserBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        nameTxt1 = new javax.swing.JTextField();
        passwordTxt1 = new javax.swing.JTextField();
        uidTxt1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        adharTxt1 = new javax.swing.JTextField();
        ulternateMoNoTxt1 = new javax.swing.JTextField();
        moNoTxt1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        sallaryTxt1 = new javax.swing.JTextField();
        qualificationTxt1 = new javax.swing.JTextField();
        occupationTxt1 = new javax.swing.JTextField();
        createUserBtn = new javax.swing.JButton();
        userTypeCmb1 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressTxt1 = new javax.swing.JTextArea();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        dd = new javax.swing.JComboBox();
        mm = new javax.swing.JComboBox();
        yy = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Setting");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fees Structure"));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(228, 251, 250));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Type");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 131, 132)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel28.setBackground(new java.awt.Color(228, 251, 250));

        monthLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monthLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthLbl1.setText("Monthly");
        monthLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 131, 132)));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monthLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monthLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel29.setBackground(new java.awt.Color(228, 251, 250));

        quarterLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quarterLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quarterLbl1.setText("Three Month");
        quarterLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 131, 132)));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quarterLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quarterLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel30.setBackground(new java.awt.Color(228, 251, 250));

        halfYearLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        halfYearLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        halfYearLbl1.setText("Six Month");
        halfYearLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 131, 132)));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(halfYearLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(halfYearLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel31.setBackground(new java.awt.Color(228, 251, 250));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Day");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 131, 132)));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel32.setBackground(new java.awt.Color(228, 251, 250));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Night");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 131, 132)));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel33.setBackground(new java.awt.Color(228, 251, 250));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Day-Night");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 131, 132)));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel34.setBackground(new java.awt.Color(228, 251, 250));

        yearLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearLbl1.setText("Year");
        yearLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 131, 132)));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yearLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yearLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dmTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dmTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dmTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dmTxtKeyReleased(evt);
            }
        });

        dtTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dtTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dtTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dtTxtKeyReleased(evt);
            }
        });

        dsTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dsTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dsTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dsTxtKeyReleased(evt);
            }
        });

        dyTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dyTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dyTxtKeyReleased(evt);
            }
        });

        nmTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nmTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nmTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nmTxtKeyReleased(evt);
            }
        });

        ntTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ntTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ntTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ntTxtKeyReleased(evt);
            }
        });

        nsTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nsTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nsTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nsTxtKeyReleased(evt);
            }
        });

        nyTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nyTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nyTxtKeyReleased(evt);
            }
        });

        dnmTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dnmTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dnmTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dnmTxtKeyReleased(evt);
            }
        });

        dntTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dntTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dntTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dntTxtKeyReleased(evt);
            }
        });

        dnsTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dnsTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dnsTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dnsTxtKeyReleased(evt);
            }
        });

        dnyTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dnyTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dnyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dnyTxtKeyReleased(evt);
            }
        });

        updateFFeesBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateFFeesBtn.setText("Update");
        updateFFeesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFFeesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dnmTxt))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nmTxt))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dmTxt))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtTxt)
                            .addComponent(ntTxt)
                            .addComponent(dntTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dsTxt)
                            .addComponent(nsTxt)
                            .addComponent(dnsTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dyTxt)
                            .addComponent(nyTxt)
                            .addComponent(dnyTxt))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateFFeesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dyTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(dsTxt)
                    .addComponent(dtTxt)
                    .addComponent(dmTxt)
                    .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nyTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(nsTxt)
                    .addComponent(ntTxt)
                    .addComponent(nmTxt)
                    .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dnmTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(dntTxt)
                    .addComponent(dnsTxt)
                    .addComponent(dnyTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(updateFFeesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("   Fees Structure    ", jPanel16);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Backup Setting"));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setText("Choose Backup Destination Folder");

        chooseFolderBtn.setText("Choose Folder");
        chooseFolderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFolderBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        folderTxt.setEditable(false);
        folderTxt.setColumns(20);
        folderTxt.setRows(5);
        jScrollPane2.setViewportView(folderTxt);

        backupBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backupBtn.setText("Proceed Backup");
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(chooseFolderBtn)
                            .addComponent(backupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 994, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(chooseFolderBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("   Export Backup   ", jPanel15);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Import Excel File ");

        jLabel41.setText("Select Excel File");

        selectExcelBtn.setText("Select File");
        selectExcelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectExcelBtnActionPerformed(evt);
            }
        });

        jScrollPane5.setBorder(null);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        excelPath.setColumns(20);
        excelPath.setRows(5);
        jScrollPane5.setViewportView(excelPath);

        importBtb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        importBtb.setText("Import Data");
        importBtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtbActionPerformed(evt);
            }
        });

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);

        console.setEditable(false);
        console.setColumns(20);
        console.setLineWrap(true);
        console.setRows(5);
        console.setWrapStyleWord(true);
        console.setBorder(null);
        jScrollPane6.setViewportView(console);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(importBtb, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(selectExcelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addGap(63, 63, 63)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(selectExcelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(importBtb, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("   Import Excel   ", jPanel14);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("   Backup    ", jPanel17);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabbedPane2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr.No.", "User ID", "Password", "Name", "Address", "Mobile Number", "Alternate Mo.No.", "Gender", "Adhar Numbeeer", "Qualification", "Occupation", "Join Date", "Sallary", "User Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setRowHeight(20);
        userTable.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane1.setViewportView(userTable);

        deleteUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteUserBtn.setText("Delete User");
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("   Users List  ", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setText("User ID");

        jLabel25.setText("Password");

        jLabel26.setText("Name");

        jLabel27.setText("Address");

        jLabel28.setText("User Type");

        nameTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxt1KeyReleased(evt);
            }
        });

        passwordTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxt1KeyReleased(evt);
            }
        });

        uidTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uidTxt1KeyReleased(evt);
            }
        });

        jLabel29.setText("Mobile No.");

        jLabel30.setText("Alternate Mo.No.");

        jLabel31.setText("Gender");

        jLabel32.setText("Adhar Number");

        adharTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adharTxt1KeyReleased(evt);
            }
        });

        ulternateMoNoTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ulternateMoNoTxt1KeyReleased(evt);
            }
        });

        moNoTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moNoTxt1KeyReleased(evt);
            }
        });

        jLabel33.setText("Qualification");

        jLabel34.setText("Occupation");

        jLabel35.setText("Join Date(dd-mm-yyyy)");

        jLabel36.setText("Sallary");

        sallaryTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sallaryTxt1KeyReleased(evt);
            }
        });

        qualificationTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qualificationTxt1KeyReleased(evt);
            }
        });

        occupationTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                occupationTxt1KeyReleased(evt);
            }
        });

        createUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createUserBtn.setText("Create User");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        userTypeCmb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Admin" }));

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        addressTxt1.setColumns(20);
        addressTxt1.setLineWrap(true);
        addressTxt1.setRows(5);
        addressTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxt1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(addressTxt1);

        male.setSelected(true);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        other.setText("Other");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        dd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));

        yy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel27))
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(uidTxt1)
                                        .addComponent(passwordTxt1)
                                        .addComponent(nameTxt1)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel34)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userTypeCmb1, 0, 265, Short.MAX_VALUE)
                                        .addComponent(occupationTxt1))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(qualificationTxt1)))
                .addGap(190, 190, 190)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(adharTxt1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(male)
                                .addGap(27, 27, 27)
                                .addComponent(female)
                                .addGap(18, 18, 18)
                                .addComponent(other)))
                        .addGap(262, 262, 262))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ulternateMoNoTxt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(moNoTxt1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sallaryTxt1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(uidTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(moNoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(passwordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(ulternateMoNoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(nameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(male)
                    .addComponent(female)
                    .addComponent(other))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(adharTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sallaryTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTypeCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qualificationTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(createUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jTabbedPane2.addTab("   Create User   ", jPanel7);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("User Setting");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTabbedPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("   User    ", jPanel18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importBtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtbActionPerformed
        // TODO add your handling code here:
        if(!excelPath.getText().isEmpty()){
            if(excelPath.getText().endsWith(".xlsx")){
              new  ImportExcel(excelPath.getText(),console);
            }else{
                JOptionPane.showMessageDialog(this, "Please choose correct excel file with extention .xlsx","Incorrect file",JOptionPane.ERROR_MESSAGE);
            }
        }else{
                JOptionPane.showMessageDialog(this, "Please choose correct excel file","File not selected",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_importBtbActionPerformed

	private void updateFFeesBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateFFeesBtnActionPerformed
		// TODO add your handling code here:

		if (!dmTxt.getText().isEmpty() && !dsTxt.getText().isEmpty() && !dsTxt.getText().isEmpty()
				&& !dyTxt.getText().isEmpty() && !nmTxt.getText().isEmpty() && !ntTxt.getText().isEmpty()
				&& !nsTxt.getText().isEmpty() && !nyTxt.getText().isEmpty() && !dnmTxt.getText().isEmpty()
				&& !dntTxt.getText().isEmpty() && !dnsTxt.getText().isEmpty() && !dnyTxt.getText().isEmpty()) {
			new FixedFeesHM(this);
		} else {
			JOptionPane.showMessageDialog(this, "All fields were Mandatory", "Sucess Park", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_updateFFeesBtnActionPerformed

	private void dmTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dmTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", dmTxt, 5);
	}// GEN-LAST:event_dmTxtKeyReleased

	private void dtTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dtTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", dtTxt, 5);
	}// GEN-LAST:event_dtTxtKeyReleased

	private void dsTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dsTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", dsTxt, 5);
	}// GEN-LAST:event_dsTxtKeyReleased

	private void dyTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dyTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", dyTxt, 5);
	}// GEN-LAST:event_dyTxtKeyReleased

	private void nmTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_nmTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", nmTxt, 5);
	}// GEN-LAST:event_nmTxtKeyReleased

	private void ntTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_ntTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", ntTxt, 5);
	}// GEN-LAST:event_ntTxtKeyReleased

	private void nsTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_nsTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", nsTxt, 5);
	}// GEN-LAST:event_nsTxtKeyReleased

	private void nyTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_nyTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", nyTxt, 5);
	}// GEN-LAST:event_nyTxtKeyReleased

	private void dnmTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dnmTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", dnmTxt, 5);
	}// GEN-LAST:event_dnmTxtKeyReleased

	private void dntTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dntTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", dntTxt, 5);
	}// GEN-LAST:event_dntTxtKeyReleased

	private void dnsTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dnsTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", dnsTxt, 5);
	}// GEN-LAST:event_dnsTxtKeyReleased

	private void dnyTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dnyTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{1,5})", dnyTxt, 5);
	}// GEN-LAST:event_dnyTxtKeyReleased

	private void maleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maleActionPerformed
		// TODO add your handling code here:
		if (male.isSelected()) {
			female.setSelected(false);
			other.setSelected(false);
		}
	}// GEN-LAST:event_maleActionPerformed

	private void otherActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_otherActionPerformed
		// TODO add your handling code here:
		if (other.isSelected()) {
			female.setSelected(false);
			male.setSelected(false);
		}
	}// GEN-LAST:event_otherActionPerformed

	private void femaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_femaleActionPerformed
		// TODO add your handling code here:
		if (female.isSelected()) {
			male.setSelected(false);
			other.setSelected(false);
		}
	}// GEN-LAST:event_femaleActionPerformed

	private void uidTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_uidTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\w]{1,19})", uidTxt1, 19);
	}// GEN-LAST:event_uidTxt1KeyReleased

	private void passwordTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_passwordTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\w~!@#$%^&*().,]{4,19})", passwordTxt1, 19);
	}// GEN-LAST:event_passwordTxt1KeyReleased

	private void nameTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_nameTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([a-z A-Z\\s]{3,49})", nameTxt1, 49);
	}// GEN-LAST:event_nameTxt1KeyReleased

	private void addressTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_addressTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\s\\w]{0,59})", addressTxt1, 59);
	}// GEN-LAST:event_addressTxt1KeyReleased

	private void moNoTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_moNoTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{10})", moNoTxt1, 10);
	}// GEN-LAST:event_moNoTxt1KeyReleased

	private void ulternateMoNoTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_ulternateMoNoTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{10})", ulternateMoNoTxt1, 10);
	}// GEN-LAST:event_ulternateMoNoTxt1KeyReleased

	private void adharTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_adharTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{12})", adharTxt1, 12);
	}// GEN-LAST:event_adharTxt1KeyReleased

	private void qualificationTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_qualificationTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\s\\w]{0,49})", qualificationTxt1, 49);
	}// GEN-LAST:event_qualificationTxt1KeyReleased

	private void occupationTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_occupationTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\s\\w]{0,19})", occupationTxt1, 19);
	}// GEN-LAST:event_occupationTxt1KeyReleased

	private void sallaryTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_sallaryTxt1KeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{0,6})", sallaryTxt1, 6);
	}// GEN-LAST:event_sallaryTxt1KeyReleased

	private void selectExcelBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		try {
		JFileChooser fc = new JFileChooser();
		fc.setDialogTitle("Select Excel File");
		FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Files", "xlsx");
		fc.setFileFilter(filter);
		fc.showOpenDialog(this);
		File f = fc.getSelectedFile();
		excelPath.setText(f.getPath());
		}catch(Exception e) {
			
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	private void chooseFolderBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chooseFolderBtnActionPerformed
		// TODO add your handling code here:
		JFileChooser f = new JFileChooser();
		f.setDialogTitle("Choose Backup Destination Directory");
		f.setApproveButtonText("Select");
		f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		f.showOpenDialog(this);

		try {
			folderTxt.setText(f.getSelectedFile().getAbsolutePath());
		} catch (Exception e) {
			System.out.println("its not exception! user cancelled selection.");
		}

	}// GEN-LAST:event_chooseFolderBtnActionPerformed

	private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backupBtnActionPerformed
		// TODO add your handling code here:
		if (folderTxt.getText().isEmpty()) {
			JOptionPane.showMessageDialog(this, "Please select destination folder for backup", "Select Directory",
					JOptionPane.ERROR_MESSAGE);
		} else {
			new GenerateZip().compress(folderTxt.getText() + "\\", "manual");
		}
	}// GEN-LAST:event_backupBtnActionPerformed

	private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createUserBtnActionPerformed
		// TODO add your handling code here:
		new UsersHM(this);
		new SetAllTable().setUserToTable(userTable);
	}// GEN-LAST:event_createUserBtnActionPerformed

	private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteUserBtnActionPerformed
		// TODO add your handling code here:
		int row = userTable.getSelectedRow();
		if (row >= 0) {
			int reply = JOptionPane.showConfirmDialog(null,
					"Are you sure, You want to delete user \"" + userTable.getValueAt(row, 1) + "\" permenently?",
					"Conform action", JOptionPane.YES_NO_OPTION);
			if (reply == JOptionPane.YES_OPTION) {
				LinkedHashMap<String, Object> lhm = new LinkedHashMap<String, Object>();
				lhm.put("ID", userTable.getValueAt(row, 1));
				if (new UsersDb().delete(lhm)) {
					((DefaultTableModel) userTable.getModel()).setRowCount(0);
					new SetAllTable().setUserToTable(userTable);
					JOptionPane.showMessageDialog(null, "User Deleted Permenently", " User Deleted",
							JOptionPane.INFORMATION_MESSAGE);
					row = -1;
				} else {
					JOptionPane.showMessageDialog(null, "User not deleted, somethig went wrong?", "User not deleted",
							JOptionPane.ERROR_MESSAGE);
				}
			}
		} else {
			JOptionPane.showMessageDialog(null, "Please select user to delete.", "User not selected",
					JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_deleteUserBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea addressTxt1;
    public javax.swing.JTextField adharTxt1;
    private javax.swing.JButton backupBtn;
    private javax.swing.JButton chooseFolderBtn;
    private javax.swing.JTextArea console;
    private javax.swing.JButton createUserBtn;
    public javax.swing.JComboBox dd;
    private javax.swing.JButton deleteUserBtn;
    public javax.swing.JTextField dmTxt;
    public javax.swing.JTextField dnmTxt;
    public javax.swing.JTextField dnsTxt;
    public javax.swing.JTextField dntTxt;
    public javax.swing.JTextField dnyTxt;
    public javax.swing.JTextField dsTxt;
    public javax.swing.JTextField dtTxt;
    public javax.swing.JTextField dyTxt;
    private javax.swing.JTextArea excelPath;
    public javax.swing.JRadioButton female;
    private javax.swing.JTextArea folderTxt;
    public static javax.swing.JLabel halfYearLbl1;
    private javax.swing.JButton importBtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    public javax.swing.JRadioButton male;
    public javax.swing.JComboBox mm;
    public javax.swing.JTextField moNoTxt1;
    public static javax.swing.JLabel monthLbl1;
    public javax.swing.JTextField nameTxt1;
    public javax.swing.JTextField nmTxt;
    public javax.swing.JTextField nsTxt;
    public javax.swing.JTextField ntTxt;
    public javax.swing.JTextField nyTxt;
    public javax.swing.JTextField occupationTxt1;
    public javax.swing.JRadioButton other;
    public javax.swing.JTextField passwordTxt1;
    public javax.swing.JTextField qualificationTxt1;
    public static javax.swing.JLabel quarterLbl1;
    public javax.swing.JTextField sallaryTxt1;
    private javax.swing.JButton selectExcelBtn;
    public javax.swing.JTextField uidTxt1;
    public javax.swing.JTextField ulternateMoNoTxt1;
    private javax.swing.JButton updateFFeesBtn;
    private javax.swing.JTable userTable;
    public javax.swing.JComboBox userTypeCmb1;
    public static javax.swing.JLabel yearLbl1;
    public javax.swing.JComboBox yy;
    // End of variables declaration//GEN-END:variables
}
