package com.reading.ui;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedHashMap;

import javax.swing.table.DefaultTableModel;

import com.reading.db.SmsDb;
import com.reading.hm.FeesHM;
import com.reading.hm.UpdateStudentHM;
import com.reading.operaton.FormatFrame;
import com.reading.operaton.SetAllTable;
import com.reading.operaton.processImage.ImageSelector;
import com.reading.regx.RegX;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sawant
 */
public class ShowStudentDetails extends javax.swing.JInternalFrame {

	LinkedHashMap<String, Object> oldDataHm;
	ResultSet rs;
	RegX regx = new RegX();

	/**
	 * Creates new form ShowStudentDetails
	 */
	public ShowStudentDetails(String sid) {

		initComponents();
		FormatFrame ff = new FormatFrame(this);
		ff.formatTable(table);
		new SetAllTable().setFeesTable(table, sid);
		mM1.setSelectedIndex(new Date().getMonth());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        qualificationTxt = new javax.swing.JTextField();
        adharTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        maleRdo = new javax.swing.JRadioButton();
        femaleRdo = new javax.swing.JRadioButton();
        otherRdo = new javax.swing.JRadioButton();
        occupationTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tempAddress = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        permenentAddress = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        shiftTypeCmb = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        admissionTypeTxt = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        browsImageLbl = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        updateImageLbl = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        parentMoNoTxt = new javax.swing.JTextField();
        alternateMoNoTxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mobileNoTxt = new javax.swing.JTextField();
        updateStudentBtn = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        ddCmb = new javax.swing.JComboBox();
        mmCmb = new javax.swing.JComboBox();
        yyyyCmb = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        submitFeesTxt1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        mM1 = new javax.swing.JComboBox();
        sbmitFeesBtn1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student Detail");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Name");

        jLabel3.setText("Temprary Address");

        jLabel5.setText("Adhar Number");

        jLabel6.setText("Qualification");

        jLabel24.setText("Gender");

        qualificationTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qualificationTxtKeyReleased(evt);
            }
        });

        adharTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adharTxtKeyReleased(evt);
            }
        });

        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtKeyReleased(evt);
            }
        });

        maleRdo.setBackground(new java.awt.Color(255, 255, 255));
        maleRdo.setSelected(true);
        maleRdo.setText("Male");
        maleRdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRdoActionPerformed(evt);
            }
        });

        femaleRdo.setBackground(new java.awt.Color(255, 255, 255));
        femaleRdo.setText("Female");
        femaleRdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRdoActionPerformed(evt);
            }
        });

        otherRdo.setBackground(new java.awt.Color(255, 255, 255));
        otherRdo.setText("Other");
        otherRdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherRdoActionPerformed(evt);
            }
        });

        occupationTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                occupationTxtKeyReleased(evt);
            }
        });

        jLabel27.setText("Occupation");

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tempAddress.setColumns(20);
        tempAddress.setRows(5);
        tempAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tempAddressKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tempAddress);

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        permenentAddress.setColumns(20);
        permenentAddress.setRows(5);
        permenentAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                permenentAddressKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(permenentAddress);

        jLabel29.setText("Permenent Address");

        jLabel36.setText("Student ID");

        idTxt.setEditable(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Shift Type");

        shiftTypeCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "Day-Night", "Night" }));
        shiftTypeCmb.setEnabled(false);

        jLabel30.setText("Admission Type");

        admissionTypeTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "For One Month", "For Three Month", "For Six Month", "For Year" }));
        admissionTypeTxt.setEnabled(false);

        jLabel17.setText("Photo");

        browsImageLbl.setText("Select Photo");
        browsImageLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsImageLblActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateImageLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateImageLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );

        jLabel26.setText("Parent's Mobile Number");

        parentMoNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parentMoNoTxtKeyReleased(evt);
            }
        });

        alternateMoNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                alternateMoNoTxtKeyReleased(evt);
            }
        });

        jLabel25.setText("Alternate Mo. Number");

        jLabel4.setText("Mobile Number");

        mobileNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileNoTxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(79, 79, 79)
                        .addComponent(mobileNoTxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel30)
                                .addComponent(jLabel17))
                            .addGap(75, 75, 75)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(shiftTypeCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(browsImageLbl)
                                            .addGap(27, 27, 27)
                                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(admissionTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel25))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(parentMoNoTxt)
                                .addComponent(alternateMoNoTxt)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mobileNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alternateMoNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(parentMoNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(shiftTypeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(admissionTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(browsImageLbl)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
        );

        updateStudentBtn.setBackground(new java.awt.Color(33, 55, 77));
        updateStudentBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateStudentBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateStudentBtn.setText("Update Detail");
        updateStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentBtnActionPerformed(evt);
            }
        });

        jLabel35.setText("Join Date(dd-MM-yyyy)");

        ddCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mmCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yyyyCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel24)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(occupationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(maleRdo)
                                    .addGap(65, 65, 65)
                                    .addComponent(femaleRdo)
                                    .addGap(72, 72, 72)
                                    .addComponent(otherRdo))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(ddCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mmCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(yyyyCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel29)
                                .addComponent(jLabel36))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameTxt)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(qualificationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(updateStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qualificationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(occupationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(maleRdo)
                    .addComponent(femaleRdo)
                    .addComponent(otherRdo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(ddCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yyyyCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Submit Fees");

        jLabel38.setText("Amount");

        submitFeesTxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitFeesTxt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        submitFeesTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFeesTxt1ActionPerformed(evt);
            }
        });
        submitFeesTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                submitFeesTxt1KeyReleased(evt);
            }
        });

        jLabel19.setText("For Month");

        mM1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan-2019", "Feb-2019", "Mar-2019", "Apr-2019", "May-2019", "Jun-2019", "Jul-2019", "Aug-2019", "Sep-2019", "Act-2019", "Nov-2019", "dec-2019" }));

        sbmitFeesBtn1.setBackground(new java.awt.Color(0, 153, 0));
        sbmitFeesBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sbmitFeesBtn1.setText("Submit");
        sbmitFeesBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmitFeesBtn1ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr.No.", "Date", "Amount", "Receiver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane6.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addGap(18, 18, 18)
                                    .addComponent(submitFeesTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(mM1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(sbmitFeesBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(submitFeesTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(mM1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(sbmitFeesBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1115, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void submitFeesTxt1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitFeesTxt1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_submitFeesTxt1ActionPerformed

	private void submitFeesTxt1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_submitFeesTxt1KeyReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_submitFeesTxt1KeyReleased

	private void sbmitFeesBtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sbmitFeesBtn1ActionPerformed
		// TODO add your handling code here:
		if (regx.validateInput("([\\d]{1,5})", submitFeesTxt1, "Please enter Fees Amount")) {
			String[] y= mM1.getSelectedItem().toString().split("-");
			new FeesHM(submitFeesTxt1.getText(), idTxt.getText(), mM1.getSelectedIndex() + 1+"-"+y[1]);
			((DefaultTableModel) table.getModel()).addRow(new Object[] {
					((DefaultTableModel) table.getModel()).getRowCount() + 1,
					new SimpleDateFormat("dd-MM-YYYY").format(new Date()), submitFeesTxt1.getText(), Home.user });

			LinkedHashMap<String, Object> lhm = new LinkedHashMap<String, Object>();
			lhm.put("ID", idTxt.getText());
//			new SmsDb().delete(lhm);
		}
	}// GEN-LAST:event_sbmitFeesBtn1ActionPerformed

	public void updateStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateStudentBtnActionPerformed
		// TODO add your handling code here:

		boolean a1 = regx.validateInput("([a-zA-Z\\s]{3,49})", nameTxt,
				"Name can not be empty and it can contain only alphabet charactors");
		boolean a2 = regx.validateInput("([\\s\\w,.]{3,49})", tempAddress, "Temprary Address can not be empty");
		boolean a3 = regx.validateInput("([\\d]{10})", mobileNoTxt,
				"Mobile number can not be empty and it should contain 10 digits");

		// non mandatory fields
		boolean a5 = regx.validateInput("([\\s\\w,.]{0,49})", permenentAddress, "Enter valid Permenent Address");
		boolean a6 = regx.validateInput("([\\d]{0,12})", adharTxt, "Enter valid Adhar number");
		boolean a7 = regx.validateInput("([\\s\\w]{0,49})", qualificationTxt,
				"Enter valid Qualification, should not contain symbols");
		boolean a8 = regx.validateInput("([\\s\\w]{0,19})", occupationTxt,
				"Enter valid Occupation, should not contain symbols");
		boolean a9 = regx.validateInput("([\\d]{0,10})", alternateMoNoTxt, "Alternate mobile number must be 10 digit");
		boolean a10 = regx.validateInput("([\\d]{0,10})", parentMoNoTxt, "Parent's mobile number must be 10 digit");

		if (a1 && a2 && a3 && a5 && a6 && a7 && a8 && a9 && a10) {
			new UpdateStudentHM(this);
		}
	}// GEN-LAST:event_updateStudentBtnActionPerformed

	private void maleRdoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maleRdoActionPerformed
		// TODO add your handling code here:
		femaleRdo.setSelected(false);
		otherRdo.setSelected(false);
	}// GEN-LAST:event_maleRdoActionPerformed

	private void femaleRdoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_femaleRdoActionPerformed
		// TODO add your handling code here:
		maleRdo.setSelected(false);
		otherRdo.setSelected(false);
	}// GEN-LAST:event_femaleRdoActionPerformed

	private void otherRdoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_otherRdoActionPerformed
		// TODO add your handling code here:
		femaleRdo.setSelected(false);
		maleRdo.setSelected(false);
	}// GEN-LAST:event_otherRdoActionPerformed

	private void browsImageLblActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_browsImageLblActionPerformed
		// TODO add your handling code here:
		new ImageSelector(updateImageLbl);
	}// GEN-LAST:event_browsImageLblActionPerformed

	private void nameTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_nameTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([a-zA-Z\\s]{3,49})", nameTxt, 49);
	}// GEN-LAST:event_nameTxtKeyReleased

	private void tempAddressKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tempAddressKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\s\\w,.]{0,49})", tempAddress, 69);
	}// GEN-LAST:event_tempAddressKeyReleased

	private void permenentAddressKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_permenentAddressKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\s\\w,.]{0,49})", permenentAddress, 69);
	}// GEN-LAST:event_permenentAddressKeyReleased

	private void adharTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_adharTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{12})", adharTxt, 12);
	}// GEN-LAST:event_adharTxtKeyReleased

	private void qualificationTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_qualificationTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\s\\w]{0,49})", qualificationTxt, 49);
	}// GEN-LAST:event_qualificationTxtKeyReleased

	private void occupationTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_occupationTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\s\\w]{0,19})", occupationTxt, 19);
	}// GEN-LAST:event_occupationTxtKeyReleased

	private void mobileNoTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_mobileNoTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{10})", mobileNoTxt, 10);
	}// GEN-LAST:event_mobileNoTxtKeyReleased

	private void alternateMoNoTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_alternateMoNoTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{10})", alternateMoNoTxt, 10);
	}// GEN-LAST:event_alternateMoNoTxtKeyReleased

	private void parentMoNoTxtKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_parentMoNoTxtKeyReleased
		// TODO add your handling code here:
		regx.isValidInput("([\\d]{10})", parentMoNoTxt, 10);
	}// GEN-LAST:event_parentMoNoTxtKeyReleased

	public void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField adharTxt;
    public javax.swing.JComboBox admissionTypeTxt;
    public javax.swing.JTextField alternateMoNoTxt;
    private javax.swing.JButton browsImageLbl;
    public javax.swing.JComboBox ddCmb;
    public javax.swing.JRadioButton femaleRdo;
    public javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox mM1;
    public javax.swing.JRadioButton maleRdo;
    public javax.swing.JComboBox mmCmb;
    public javax.swing.JTextField mobileNoTxt;
    public javax.swing.JTextField nameTxt;
    public javax.swing.JTextField occupationTxt;
    public javax.swing.JRadioButton otherRdo;
    public javax.swing.JTextField parentMoNoTxt;
    public javax.swing.JTextArea permenentAddress;
    public javax.swing.JTextField qualificationTxt;
    private javax.swing.JButton sbmitFeesBtn1;
    public javax.swing.JComboBox shiftTypeCmb;
    private javax.swing.JTextField submitFeesTxt1;
    private javax.swing.JTable table;
    public javax.swing.JTextArea tempAddress;
    public javax.swing.JLabel updateImageLbl;
    private javax.swing.JButton updateStudentBtn;
    public javax.swing.JComboBox yyyyCmb;
    // End of variables declaration//GEN-END:variables
}
